# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain Java versions, and provides a first line of defence against bad commits.

name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [
          "8", # Why not?
          "17", # Old LTS
          "21" # Current LTS
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: gradle/wrapper-validation-action@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Grant execute permission
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - if: matrix.java == '17'
        name: Upload a Build Artifact
        uses: actions/upload-artifact@v6
        with: 
          name: modid
          path: build/libs/*.jar
